name: Build and Package LetheLauncher

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore LetheLauncher.sln --runtime win-x64

    - name: Build solution
      run: dotnet build LetheLauncher.sln --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish LetheLauncher/LetheLauncher.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish

    - name: Create distribution package
      shell: powershell
      run: |
        # Create distribution directory
        mkdir -p ./publish/distribution

        # Copy main executable
        Copy-Item ./publish/LimbusCompany.exe ./publish/distribution/

        # Copy required native DLLs if they exist
        if (Test-Path ./publish/av_libglesv2.dll) { Copy-Item ./publish/av_libglesv2.dll ./publish/distribution/ }
        if (Test-Path ./publish/libHarfBuzzSharp.dll) { Copy-Item ./publish/libHarfBuzzSharp.dll ./publish/distribution/ }
        if (Test-Path ./publish/libSkiaSharp.dll) { Copy-Item ./publish/libSkiaSharp.dll ./publish/distribution/ }

        # List files in distribution
        Write-Host "Distribution package created:"
        Get-ChildItem ./publish/distribution/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LetheLauncher-Distribution
        path: ./publish/distribution/
        if-no-files-found: error

    - name: Create release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/distribution/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
